export type MnfsErrorCode =
  | 'INVALID_ARGUMENTS'
  | 'WSL2_REQUIRED'
  | 'LINUX_FILESYSTEM_REQUIRED'
  | 'NODE_VERSION_UNSUPPORTED'
  | 'REQUIRED_TOOL_MISSING'
  | 'NOT_GIT_REPOSITORY'
  | 'PROJECT_IDENTITY_INVALID'
  | 'PROJECT_NOT_INITIALIZED'
  | 'PROJECT_INITIALIZATION_FAILED'
  | 'RUNTIME_HOME_INVALID'
  | 'PLAN_INVALID'
  | 'PLAN_NOT_FOUND'
  | 'PLAN_REVISION_CONFLICT'
  | 'PLAN_APPROVAL_CONFLICT'
  | 'PLAN_BLOCKED'
  | 'PLAN_MATERIALIZATION_FAILED'
  | 'LAVISH_NOT_FOUND'
  | 'LAVISH_COMMAND_FAILED'
  | 'EXECUTION_TARGET_INVALID'
  | 'EXECUTION_CONTRACT_CONFLICT'
  | 'EXECUTION_SOURCE_INVALID'
  | 'EXECUTION_SOURCE_CHANGED'
  | 'EXECUTION_SOURCE_REMOTE_PRESENT'
  | 'EXECUTION_SOURCE_SHARED_OBJECTS'
  | 'SCHEMA_VERSION_UNSUPPORTED'
  | 'SCHEMA_MIGRATION_INVALID'
  | 'WRITE_TRACK_CONFLICT'
  | 'WRITE_TRACK_NOT_ABANDONABLE'
  | 'ATTEMPT_CONFLICT'
  | 'WORKER_RUN_CONFLICT'
  | 'CLAIM_CONFLICT'
  | 'CLAIM_IDEMPOTENCY_CONFLICT'
  | 'CLAIM_RESULT_TREE_INVALID'
  | 'CONCURRENCY_CONFLICT'
  | 'LEASE_CONFLICT'
  | 'LEASE_IDEMPOTENCY_CONFLICT'
  | 'LEASE_OPERATION_IN_PROGRESS'
  | 'LEASE_OPERATION_OWNER_UNKNOWN'
  | 'LEASE_ACTION_INCONCLUSIVE'
  | 'LEASE_FENCE_CONFLICT'
  | 'LEASE_RELEASE_BLOCKED_DIRTY'
  | 'LEASE_RELEASE_BLOCKED_UNKNOWN'
  | 'TREEHOUSE_NOT_FOUND'
  | 'TREEHOUSE_VERSION_UNSUPPORTED'
  | 'TREEHOUSE_COMMAND_FAILED'
  | 'TREEHOUSE_TIMEOUT'
  | 'TREEHOUSE_OUTPUT_INVALID'
  | 'TREEHOUSE_OBSERVATION_CONFLICT'
  | 'GIT_WORKTREE_INVALID'
  | 'GIT_OBJECT_INVALID'
  | 'RECOVERY_DIVERGENCE'
  | 'INTERNAL_ERROR';

export class MnfsError extends Error {
  readonly code: MnfsErrorCode;
  readonly exitCode: number;
  readonly remediation: string | undefined;

  constructor(
    code: MnfsErrorCode,
    message: string,
    options: { readonly exitCode?: number; readonly remediation?: string } = {},
  ) {
    super(message);
    this.name = 'MnfsError';
    this.code = code;
    this.exitCode = options.exitCode ?? 1;
    this.remediation = options.remediation;
  }
}
